server:
  port: 8001


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:7001/eureka,http://eureka-server2:7002/eureka  #集群配置
#  server:
#    enable-self-preservation: false
spring:
  application:
    name: cloud-provider-payment-hystrix
#    eviction-interval-timer-in-ms: 2000