server:
  port: 8000


spring:
  application:
    name: consul-provider-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
