server:
  port: 8000

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server1:7001/eureka,http://eureka-server2:7002/eureka  #集群配置