server:
  port: 8000


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server1:7001/eureka,http://eureka-server2:7002/eureka  #集群配置

spring:
  application:
    name: cloud-provider-order-hystrix
