server:
  port: 7001

eureka:
  instance:
    hostname: eureka-server1  #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
        #defaultZone: http://eureka-server2:7002/eureka/    #集群配置 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
        defaultZone: http://localhost:7001/eureka/          #单机配置
  server:
    enable-self-preservation: false                        #关闭自我保护
    eviction-interval-timer-in-ms: 2000
